spring:
  logging:
    level:
      root: DEBUG
  cloud:
    kubernetes:
      config:
        enabled: true
        name: default-name
        namespace: components-selector
        sources:
          - namespace: components-selector
            name: config-map-be
  codec:
    max-in-memory-size: 500KB
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://postgres-first-postgresql.default.svc.cluster.local:5432/local"
    username: postgres
    password: kFVPCPZC25
  r2dbc:
    url: "r2dbc:postgresql://postgres-first-postgresql.default.svc.cluster.local:5432/local?schema=public"
    username: postgres
    password: kFVPCPZC25
  flyway:
    url: "jdbc:postgresql://postgres-first-postgresql.default.svc.cluster.local:5432/local"
    user: postgres
    password: kFVPCPZC25
    table: schema_history
    clean-disabled: false
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0
    out-of-order: true
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
